### ISSUE TITLE
FEATURE: is it possible to remove the setup outputs?

### ISSUE THREAD

**Issue by pysan3** [mrcjkb/lua-typecheck-action#51]
These two types of output from setup action takes too much to scroll, and it is very tedious to get to the actual type errors.

Is it possible to suppress these outputs?

- `  /nix/store/zzwqcifb2hgm1qii6ixh86cjryzlf5zh-linux-headers-6.1`
- `copying path '/nix/store/5w8plg5yf0iw06h7lnfqwlr23wd2jgpz-base-orphans-0.8.7-doc' from 'https://cache.nixos.org'...`

![image](https://github.com/mrcjkb/lua-typecheck-action/assets/41065736/f00120c3-327a-40cb-b469-bc6a34fcc096)

Thanks in advance.

An example of a failing action: https://github.com/pysan3/neo-tree.nvim/actions/runs/7784734367/job/21225838660

**Comment by mrcjkb** [comment]
Hey :wave: 

Thanks for the suggestion. I don't think it's possible to suppress the install nix action output, but I've added a `--quiet` flag to suppress the nix store outputs.

**Comment by pysan3** [comment]
Thanks @mrcjkb !
